routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*Route::get('/', function () {
    return view('welcome');
})->name('/');*/

Route::get('/queue-work', function () {
    $exitCode = Artisan::call('queue:work');
    return redirect('/');
});

// Clear Cache Url
Route::get('/clear-cache', function () {
    $exitCode = Artisan::call('cache:clear');
    $exitCode = Artisan::call('route:clear');
    $exitCode = Artisan::call('view:clear');
    $exitCode = Artisan::call('config:clear');
    return redirect('/');
});
// ---------------
// Storage Link Url
Route::get('/storage-link', function () {
    $exitCode = Artisan::call('storage:link');
    return redirect('/');
});

Route::get('/', array(
    'as' => '/',
    'uses' => 'Front\IndexController@index'
));

Route::get('about-us', array(
    'as' => 'about',
    'uses' => 'Front\IndexController@about'
));

/*Route::get('book-an-appointment', array('as' => 'appointment',
    'uses' => 'Front\IndexController@appointment'));

Route::get('appointment-verify/{dt?}', array('as' => 'appointment-verify',
    'uses' => 'Front\IndexController@appointmentValidate'));

Route::any('appointment-save', array('as' => 'appointment-save',
    'uses' => 'Front\IndexController@appointmentStore'));*/

Route::get('services', array(
    'as' => 'services',
    'uses' => 'Front\IndexController@services'
));

Route::get('service/{title?}', array(
    'as' => 'service-detail',
    'uses' => 'Front\IndexController@serviceDetail'
));

Route::get('fee-schedules', array(
    'as' => 'free-consultation',
    'uses' => 'Front\IndexController@freeConsultation'
));

Route::get('contact-us', array(
    'as' => 'contact',
    'uses' => 'Front\IndexController@contact'
));

Route::get('our-team', ['as' => 'our-team', 'uses' => 'Front\IndexController@ourTeam']);
Route::get('team-details/{id}', 'Front\IndexController@teamDetail')->name('team-detail');

Route::get('download-form', array(
    'as' => 'downloadform',
    'uses' => 'Front\IndexController@downloadform'
));


Route::get('enquiry', array(
    'as' => 'enquiry',
    'uses' => 'Front\IndexController@enquiry'
));

Route::get('testmonial', 'Front\IndexController@testimonial')->name('testimonial');


Route::any('contact-send', array(
    'as' => 'contact-send',
    'uses' => 'Front\IndexController@contactStore'
));

Route::any('consultation-send', array(
    'as' => 'consultation-send',
    'uses' => 'Front\IndexController@consultationStore'
));

Route::any('subscribe-store', array(
    'as' => 'subscribe-store',
    'uses' => 'Front\IndexController@subscribeStore'
));

Route::get('/login', 'Front\WebsiteUserController@showLogin')->name('frontend.user.login');
Route::get('/new-login', function () {
    return view('front.login-page');
})->name('frontend.user.new-login');
Route::post('/login', 'Front\WebsiteUserController@login')->name('frontend.user.dologin');
Route::get('/logout', function () {
    session()->forget(['user_id', 'user_name']);
    return redirect()->back();
})->name('frontend.user.logout');
Route::get('/profile', 'Front\WebsiteUserController@profile')->name('frontend.user.profile');
Route::post('/profile', 'Front\WebsiteUserController@updateProfile')->name('frontend.user.profile.update');
Route::get('/register', 'Front\WebsiteUserController@showRegiter')->name('frontend.user.register');
Route::post('/register', 'Front\WebsiteUserController@register')->name('frontend.user.doregister');
// Route::get('google-login', function () {
//     return Socialite::driver('google')->redirect();
// });
Route::get('google-login/callback', 'Front\WebsiteUserController@googleLogin');

/******************* FOR ADMIN *****************/
Route::group(['prefix' => 'eadmin'], function () {
    Route::get('/', 'Auth\LoginController@login')->name('admin.login');
    Route::get('login', 'Auth\LoginController@login')->name('login');
    Route::post('do-login', 'Auth\LoginController@doLogin')->name('admin.dologin');
});

Route::prefix('eadmin')->middleware(['auth', 'prevent-back'])->group(function () {
    Route::any('logout', 'Auth\LoginController@authLogout')->name('logout');
    Route::get('dashboard', 'DashboardController@index')->name('home');

    Route::any('web-setting', array(
        'as' => 'setting.web-setting',
        'uses' => 'SettingController@webSetting'
    ));

    // User Routes
    Route::resource(
        'user',
        'UserController',
        [
            'names' => [
                'index'     => 'user.index',
                'create'    => 'user.create',
                'store'     => 'user.store',
                'edit'      => 'user.edit',
                'update'    => 'user.update',
            ],
            'except' => ['show', 'destroy']
        ]
    );

    Route::get('change-password', 'UserController@changePassword')->name('user.changePassword');
    Route::post('update-password', 'UserController@updatePassword')->name('user.updatePassword');

    Route::any('user/paginate/{page?}', [
        'as' => 'user.paginate',
        'uses' => 'UserController@userPaginate'
    ]);
    Route::any('user/action', [
        'as' => 'user.action',
        'uses' => 'UserController@userAction'
    ]);
    Route::any('user/toggle/{id?}', [
        'as' => 'user.toggle',
        'uses' => 'UserController@userToggle'
    ]);
    Route::get('user/drop/{id?}', [
        'as' => 'user.drop',
        'uses' => 'UserController@drop'
    ]);

    // Services Routes
    Route::resource(
        'services',
        'ServicesController',
        [
            'names' => [
                'index'     => 'services.index',
                'create'    => 'services.create',
                'store'     => 'services.store',
                'edit'      => 'services.edit',
                'update'    => 'services.update'
            ],
            'except' => ['show', 'destroy']
        ]
    );

    Route::any('services/paginate/{page?}', [
        'as' => 'services.paginate',
        'uses' => 'ServicesController@servicePaginate'
    ]);

    Route::any('services/sort', [
        'as' => 'services.sort',
        'uses' => 'ServicesController@sortingService'
    ]);

    Route::any('services/toggle/{id?}', [
        'as' => 'services.toggle',
        'uses' => 'ServicesController@serviceToggle'
    ]);

    Route::any('services/featured/{id?}', [
        'as' => 'services.featured',
        'uses' => 'ServicesController@markedFeatured'
    ]);

    Route::get('services/drop/{id?}', [
        'as' => 'services.drop',
        'uses' => 'ServicesController@drop'
    ]);

    Route::any('services-upload-pictures/{id?}', [
        'as' => 'services.upload',
        'uses' => 'ServicesController@pictureUpload'
    ]);

    Route::any('services-drop-pictures/{id?}/{file?}', [
        'as' => 'services.picture-delete',
        'uses' => 'ServicesController@pictureDelete'
    ]);

    // Slider Banner Routes
    Route::resource(
        'slider-banner',
        'SliderBannerController',
        [
            'names' => [
                'index'     => 'slider-banner.index',
                'create'    => 'slider-banner.create',
                'store'     => 'slider-banner.store',
                'edit'      => 'slider-banner.edit',
                'update'    => 'slider-banner.update'
            ],
            'except' => ['show', 'destroy']
        ]
    );

    Route::any('slider-banner/paginate/{page?}', [
        'as' => 'slider-banner.paginate',
        'uses' => 'SliderBannerController@sliderBannerPaginate'
    ]);

    Route::any('slider-banner/toggle/{id?}', [
        'as' => 'slider-banner.toggle',
        'uses' => 'SliderBannerController@sliderBannerToggle'
    ]);

    Route::any('slider-banner/sort', [
        'as' => 'slider-banner.sort',
        'uses' => 'SliderBannerController@sortingSliderBanner'
    ]);

    Route::any('slider-banner/featured/{id?}', [
        'as' => 'slider-banner.featured',
        'uses' => 'SliderBannerController@markedFeatured'
    ]);

    Route::get('slider-banner/drop/{id?}', [
        'as' => 'slider-banner.drop',
        'uses' => 'SliderBannerController@drop'
    ]);

    // --------------
    // Download Form Routes
    Route::resource(
        'download-form',
        'DownloadFormController',
        [
            'names' => [
                'index'     => 'download-form.index',
                'create'    => 'download-form.create',
                'store'     => 'download-form.store',
                'edit'      => 'download-form.edit',
                'update'    => 'download-form.update'
            ],
            'except' => ['show', 'destroy']
        ]
    );

    Route::any('download-form/paginate/{page?}', [
        'as' => 'download-form.paginate',
        'uses' => 'DownloadFormController@downloadFormPaginate'
    ]);

    Route::any('download-form/toggle/{id?}', [
        'as' => 'download-form.toggle',
        'uses' => 'DownloadFormController@formToggle'
    ]);

    Route::any('download-form/sort', [
        'as' => 'download-form.sort',
        'uses' => 'DownloadFormController@sortingdownloadForm'
    ]);

    Route::any('download-form/featured/{id?}', [
        'as' => 'download-form.featured',
        'uses' => 'DownloadFormController@markedFeatured'
    ]);

    Route::get('slider-banner/drop/{id?}', [
        'as' => 'slider-banner.drop',
        'uses' => 'DownloadFormController@drop'
    ]);

    // ---------------------------------------------

    // Pages Routes
    Route::resource(
        'cms-pages',
        'PageController',
        [
            'names' => [
                'index'     => 'pages.index',

resources/views/pages/create.blade.php
@extends('layouts.admin')
@section('content')
<div id="page-wrapper">
    <!-- start: PAGE HEADER -->
    <div class="row topheading-row">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <a class="btn btn-sm btn-danger pull-right margintop10 marginbottom10  _back" href="javascript:void(0)"> <i class="fa fa-arrow-left fa-fw"></i> {!! lang('common.back') !!} </a>
            <h1 class="page-header margintop10">{!! lang('common.create_heading', lang('pages.page')) !!}</h1>
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- end: PAGE HEADER -->
    <!-- start: PAGE CONTENT -->

    {{--for message rendering--}}
    @include('layouts.messages')
    <div class="row">
        <div class="col-md-12">
        {!! Form::open(array('method' => 'POST', 'route' => array('pages.store'),  'id' => 'ajaxSave', 'class' => 'form-horizontal')) !!}
        <div class="col-md-6 paddingleft0">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <i class="fa fa-external-link-square"></i>
                    Page Detail
                </div>
                <div class="panel-body">
                    <div class="row">

                        <div class="col-sm-11 marginleft20">
                            {!! Form::text('byline', null, array('class' => 'form-control', 'placeholder' => 'Page Name', 'id' => 'byline')) !!}
                        </div>

                        <div class="col-sm-11 margintop20 marginleft20">
                            <div>
                                {!! Form::textarea('title', null, array('class' => 'form-control', 'placeholder' => 'Page Title', 'id' => 'title', 'size' => '10x3')) !!}
                            </div>
                            <span class="help-block"><i class="fa fa-info-circle"></i> Maximum 255 characters </span>
                        </div>

                        <div class="col-sm-11 marginleft20">
                            {!! Form::textarea('short_intro', null, array('class' => 'form-control', 'placeholder' => 'Enter short intro', 'size' => '10x3')) !!}
                        </div>

                        <div class="col-sm-11 marginleft20"> <br/>
                            {!! Form::label('status', 'Status', array('class' => 'col-sm-2 control-label')) !!}
                            <div class="col-sm-1 margintop10">
                                {!! Form::checkbox('status', '1', true) !!}
                            </div>
                        </div>
                    </div>

                    <div class="col-sm-12 margintop20 text-center">
                        <div class="form-group">
                            {!! Form::submit('Save', array('class' => 'btn btn-primary btn-lg')) !!}
                        </div>
                    </div>

                </div>
            </div>
            <!-- end: TEXT FIELDS PANEL -->
        </div>

        <div class="col-md-6 paddingright0">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <i class="fa fa-external-link-square"></i>
                    SEO Meta Details
                </div>
                <div class="panel-body">
                    <div class="row marginleft10">

                        <div class="form-group">
                            <div class="col-sm-11">
                                {!! Form::textarea('meta_title', null, array('class' => 'form-control','placeholder' => 'Page Title',  'size' => '10x2', 'id' => 'meta_title')) !!}
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-sm-11">
                                {!! Form::textarea('meta_keywords', null, array('class' => 'form-control','placeholder' => 'Meta Keywords',  'size' => '10x2', 'id' => 'meta_keyword')) !!}
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-sm-11">
                                {!! Form::textarea('meta_description', null, array('class' => 'form-control','placeholder' => 'Meta Description',  'size' => '10x3', 'id' => 'meta_description')) !!}
                            </div>
                        </div>

                    </div>
                </div>
            </div>
            <!-- end: TEXT FIELDS PANEL -->
        </div>

        <div class="col-md-12 paddingleft0 paddingright0">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <i class="fa fa-external-link-square"></i>
                    Full Page Detail
                </div>
                <div class="panel-body">
                    <div class="form-group">
                        <div class="col-sm-12">
                            {!! Form::textarea('full_detail', null, array('class' => 'ckeditor form-control', 'size' => '10x5')) !!}
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-md-12 hidden">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <i class="fa fa-external-link-square"></i>
                    Embedd Video
                </div>
                <div class="panel-body">
                    <div class="form-group">
                        {!! Form::label('youtube_video', 'Youtube Video', array('class' => 'col-sm-2 control-label')) !!}
                        <div class="col-sm-8">
                            {!! Form::textarea('youtube_video', null, array('class' => 'form-control', 'size' => '10x2')) !!}
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-sm-12 text-center">
            <div class="form-group">
                {!!  Form::submit('Save', array('class' => 'btn btn-primary btn-lg'))  !!}
            </div>
        </div>
        {!! Form::close() !!}
    </div>
    </div>
</div>
@stop

resources/views/pages/edit.blade.php
    @extends('layouts.admin')
@section('content')
<div id="page-wrapper">
    <!-- start: PAGE HEADER -->
    <div class="row topheading-row">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <a class="btn btn-sm btn-danger pull-right margintop10 marginbottom10 _back" href="javascript:void(0)"> <i class="fa fa-arrow-left fa-fw"></i> {!! lang('common.back') !!} </a>
            <h1 class="page-header margintop10"> {!! lang('common.edit_heading', lang('pages.page')) !!} #{!! $result->title !!}</h1>
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- end: PAGE HEADER -->
    <!-- start: PAGE CONTENT -->
    
    {{--for message rendering--}}
    @include('layouts.messages')
    <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 padding0">
            {!! Form::model($result, array('route' => array('pages.update', $result->id), 'method' => 'PATCH',  'id' => 'ajaxSave', 'class' => 'form-horizontal')) !!}

            <div class="col-md-6">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <i class="fa fa-external-link-square"></i>
                        Page Detail
                    </div>
                    <div class="panel-body">
                        <div class="row">

                            <div class="col-sm-11 marginleft20">
                                {!! Form::text('byline', null, array('class' => 'form-control', 'placeholder' => 'Page Name', 'id' => 'byline')) !!}
                            </div>

                            <div class="col-sm-11 margintop20 marginleft20">
                                <div>
                                    {!! Form::textarea('title', null, array('class' => 'form-control', 'placeholder' => 'Page Title', 'id' => 'title', 'size' => '10x3')) !!}
                                </div>
                                <span class="help-block"><i class="fa fa-info-circle"></i> Maximum 255 characters </span>
                            </div>

                            <div class="col-sm-11 marginleft20">
                                {!! Form::textarea('short_intro', null, array('class' => 'form-control', 'placeholder' => 'Enter short intro', 'size' => '10x3')) !!}
                            </div>

                            <div class="col-sm-11 marginleft20"> <br/>
                                {!! Form::label('status', 'Status', array('class' => 'col-sm-2 control-label')) !!}
                                <div class="col-sm-1 margintop10">
                                    {!! Form::checkbox('status', '1', ($result->status == 1) ? true : false) !!}
                                </div>
                            </div>

                        </div>

                        <div class="col-sm-12 margintop20 text-center">
                            <div class="form-group">
                                {!! Form::submit('Update', array('class' => 'btn btn-primary btn-lg')) !!}
                            </div>
                        </div>

                    </div>
                </div>
                <!-- end: TEXT FIELDS PANEL -->
            </div>

            <div class="col-md-6">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <i class="fa fa-external-link-square"></i>
                        SEO Meta Details
                    </div>
                    <div class="panel-body">
                        <div class="row marginleft10">

                            <div class="form-group">
                                <div class="col-sm-11">
                                    {!! Form::textarea('meta_title', null, array('class' => 'form-control','placeholder' => 'Page Title',  'size' => '10x2', 'id' => 'meta_title')) !!}
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-sm-11">
                                    {!! Form::textarea('meta_keywords', null, array('class' => 'form-control','placeholder' => 'Meta Keywords',  'size' => '10x2', 'id' => 'meta_keyword')) !!}
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-sm-11">
                                    {!! Form::textarea('meta_description', null, array('class' => 'form-control','placeholder' => 'Meta Description',  'size' => '10x3', 'id' => 'meta_description')) !!}
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
                <!-- end: TEXT FIELDS PANEL -->
            </div>

            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <i class="fa fa-external-link-square"></i>
                        Full Page Detail
                    </div>
                    <div class="panel-body">
                        <div class="form-group">
                            <div class="col-sm-12">
                                {!! Form::textarea('full_detail', $result->full_detail, array('class' => 'ckeditor form-control', 'size' => '10x5')) !!}
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-md-12 hidden">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <i class="fa fa-external-link-square"></i>
                        Embedd Video
                    </div>
                    <div class="panel-body">
                        <div class="form-group">
                            {!! Form::label('youtube_video', 'Youtube Video', array('class' => 'col-sm-2 control-label')) !!}
                            <div class="col-sm-8">
                                {!! Form::textarea('youtube_video', null, array('class' => 'form-control', 'size' => '10x2')) !!}
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-sm-12 text-center">
                <div class="form-group">
                    {!! Form::submit('Update', array('class' => 'btn btn-primary btn-lg')) !!}
                </div>
            </div>
            {!! Form::close() !!}
        </div>

        <div class="col-sm-12 col-md-12">

        <?php
        $path = Config::get('constants.UPLOADS');
        $folderPath = ROOT . $path[1];

        $folder =  $folderPath . '/';
        $files = glob($folder . $result->id . "__*");
        ?>
        <!-- start: DROPZONE PANEL -->
            <div class="panel panel-default">
                <div class="panel-heading">

                    <?php if( count($files) > 0) { ?>
                        {{--<a class="btn btn-xs btn-primary pull-right"  href="{!! route('admin.news-article.zip-download', [$detail->fn_id]) !!}"><i class="fa-times fa fa-cloud-download"></i> Download Images</a>--}}
                    <?php } ?>

                    <i class="fa fa-external-link-square"></i>
                    Upload Page Images By Drag & Drop
                </div>
                <div class="panel-body">
                    <?php

                        if (count($files) > 0 ) {
                            $iteration = 0;
                            foreach ($files as $imagePath) {

                            $files = explode('/', $imagePath);

                            $total = count($files);
                            $file = $files[$total - 1];

                            $thumb = $folder . 'thumbs/' . $file;
                            $main = $folder . $file;

                            $startPosition = strpos($thumb, $path[1]);
                            $fileLocation = substr($thumb, $startPosition);

                            $startPositionMain = strpos($main, $path[1]);
                            $fileLocationMain = substr($main, $startPosition);

                            if ( file_exists($imagePath) && file_exists($thumb) ) {
                                if ( $iteration++ == 6 ) {
                                //segregate thumbs after 6 by col-md-12
                    ?>

                    <div class="col-md-12">    </div>

                    <?php } ?>

                    <div class="col-md-2">
                        <div class="thumbnail" style="position:reletive;">
                            {!! HTML::image($fileLocation) !!}
                            <span class="btn btn-xs btn-primary copy-link text-center margintop0" style="position:absolute; right:30px; top:0;" title="Copied" data-clipboard-text="{!! asset($path[1] . '/'.$file) !!}">Copy</span>
                            <span class="text-center margintop0" style="position:absolute; right:6px; top:0;">
                                <a data-original-title="Delete" data-placement="right" class="btn btn-xs btn-danger tooltips __drop"  href="javascript:void(0);" data-route="{!! route('pages.picture-delete', [$result->id, base64_encode($file)]) !!}" data-message="Are you sure? want to delete this image."><i class="fa-times fa fa-white"></i></a>
                            </span>
                        </div>
                    </div>
                    <?php } } } ?>

                    {!! Form::open(array('route' => array('pages.upload', 'id' => $result->id), 'id' => 'my-awesome-dropzone', 'class' => 'dropzone col-md-12')) !!}

                    {!! Form::close() !!}
                </div>
            </div>
            <!-- end: DROPZONE PANEL -->
        </div>
    </div>
</div>
<!-- /#page-wrapper -->
<script>
    var clipboard = new Clipboard('.copy-link');
    clipboard.on('success', function(e) {
        $(e.trigger).attr('title', 'Copied').tooltip('fixTitle').tooltip('show');
        $(e.trigger).hover(function(){
            $(this).tooltip("hide");
        });
    });
</script>
@stop

resources/views/pages/index.blade.php
@extends('layouts.admin')
@section('content')

<div id="page-wrapper">
    <div class="row topheading-row">
			<div class="col-lg-12 col-md-12 col-sm-6 col-xs-12">
			<a class="btn btn-sm btn-primary pull-right margintop10" href="{!! route('pages.create') !!}"> <i class="fa fa-plus fa-fw"></i> {!! lang('common.create_heading', lang('pages.page')) !!} </a>
			<h1 class="page-header margintop10"> {!! lang('pages.pages') !!} </h1>
		</div>
        <!-- /.col-lg-12 -->
    </div>
 	{{--for message rendering --}}
    @include('layouts.messages')

	<div class="row">

		<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
			<!-- start: BASIC TABLE PANEL -->
			<div class="panel panel-primary" style="position: static;">
				<div class="panel-heading">
					<i class="fa fa-external-link-square"></i> &nbsp;
					{!! lang('pages.pages_list') !!}
				</div>
				<div class="panel-body">
					<div class="col-md-3 col-lg-3 col-md-3 col-sm-6 col-xs-12 text-right pull-right padding0 marginbottom10">
						{!! lang('common.per_page') !!}: {!! Form::select('name', ['20' => '20', '40' => '40', '100' => '100', '200' => '200', '300' => '300'], '20', ['id' => 'per-page']) !!}
					</div>
					<div class="col-lg-3 col-md-3 col-sm-6 col-xs-12 padding0 marginbottom10">
						{!! Form::hidden('page', 'search') !!}
						{!! Form::hidden('_token', csrf_token()) !!}
						{!! Form::text('name', null, array('class' => 'form-control live-search', 'placeholder' => "Search Page")) !!}
					</div>
					<table id="paginate-load" data-route="{!! route('pages.paginate') !!}" data-sorting="{{ route('pages.sorter') }}" class="table table-responsive table-hover clearfix margin0 col-md-12 padding0 table-fullbox">
					</table>
				</div>
			</div>
			<!-- end: BASIC TABLE PANEL -->
		</div>	
	</div>
</div>
<!-- /#page-wrapper -->
@stop

resources/views/pages/load_data.blade.php
<thead>
<tr>
    <th width="5%" class="text-center">{!! lang('common.id') !!}</th>
    <th width="30%">
        {!! lang('common.name') !!}
    </th>
     <th class="text-center"> {!! lang('common.status') !!} </th>
     <th class="text-center">
         {!! lang('common.action') !!}
     </th>
</tr>
</thead>
<tbody>
<?php $index = 1; ?>
@foreach($data as $detail)
    <tr id="order_{!! $detail->id !!}">
        <td class="text-center">{!! pageIndex($index++, $page, $perPage) !!}</td>
        <td>
         <a title="{!! lang('common.edit') !!}" href="{{ route('pages.edit', [$detail->id]) }}">
            {!! $detail->byline !!}
         </a>
        </td>
        <td class="text-center">
            <a title="{!! lang('common.status') !!}" href="javascript:void(0);" class="toggle-status" data-message="{!! lang('messages.change_status') !!}" data-route="{!! route('pages.toggle', $detail->id) !!}">
                {!! HTML::image('public/assets/images/' . $detail->status . '.gif') !!}
            </a>
        </td>
        <td class="text-center col-md-1">
            <a title="{!! lang('common.edit') !!}" class="btn btn-xs btn-primary" href="{!! route('pages.edit', [$detail->id]) !!}"><i class="fa fa-edit"></i></a>
            {{--<a title="{!! lang('common.delete') !!}" class="btn btn-xs btn-danger __drop" data-route="{!! route('pages.drop', [$detail->id]) !!}" data-message="{!! lang('messages.sure_delete', string_manip(lang('pages.pages'))) !!}" href="javascript:void(0)"><i class="fa fa-times"></i></a>--}}
        </td>
    </tr>
@endforeach
@if (count($data) < 1)
    <tr>
        <td class="text-center" colspan="7"> {!! lang('messages.no_data_found') !!} </td>
    </tr>
@else
    <tr class="margintop10">
        <td colspan="7">
            {!! paginationControls($page, $total, $perPage) !!}
        </td>
    </tr>
@endif
</tbody>

resources/views/pages/process.blade.php
@extends('layouts.admin')

@section('content')
    <!-- start: PAGE -->
    <div id="page-wrapper">
    <!-- start: PAGE HEADER -->
    <div class="row">
        <div class="col-sm-12">
            &nbsp;<!-- end: PAGE TITLE & BREADCRUMB -->
        </div>
    </div>
    <!-- end: PAGE HEADER -->
    <!-- start: PAGE CONTENT -->
    <div class="col-md-12">
        <div class="alert alert-block alert-success fade in">
            <button data-dismiss="alert" class="close" type="button">
                &times;
            </button>
            <h4 class="alert-heading"><i class="fa fa-check-circle"></i> Success!</h4>
            <p>
                Page Created successfully. <br /><br />
            </p>
            <p>
                <a href="{{ route('pages.create') }}" class="btn btn-success">
                    Create More Page
                </a>
                <a href="{{ route('pages.edit', ['id' => $id]) }}" class="btn btn-primary">
                    Edit Page Detail
                </a>
                <a href="{{ route('pages.index') }}" class="btn btn-default">
                    List Pages
                </a>
            </p>
        </div>
    </div>
@stop